# Generated by Django 4.2.7 on 2023-12-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.TextField(blank=True, null=True)),
                ('numero', models.TextField(blank=True, null=True)),
                ('localidad', models.TextField(blank=True, null=True)),
                ('provincia', models.TextField(blank=True, null=True)),
                ('codigo_postal', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'direccion',
                'managed': False,
            },
        ),
    ]
