# Generated by Django 4.2.7 on 2023-12-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('numero', models.TextField(db_column='Numero')),
                ('cvv', models.IntegerField(blank=True, db_column='CVV', null=True)),
                ('fechaotorgamiento', models.DateField(blank=True, db_column='FechaOtorgamiento', null=True)),
                ('fechaexpiracion', models.DateField(blank=True, db_column='FechaExpiracion', null=True)),
                ('tipotarjeta', models.TextField(blank=True, db_column='TipoTarjeta', null=True)),
                ('id', models.IntegerField(blank=True, db_column='ID', null=True)),
                ('tarjeta_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tarjeta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoTarjeta',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.TextField(db_column='Nombre')),
            ],
            options={
                'db_table': 'tipo_tarjeta',
                'managed': False,
            },
        ),
    ]
